### ISSUE TITLE
Annotation stores returned from different datasets than specified dataset

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node#106]
<img width="1271" alt="Screen Shot 2020-12-06 at 3 37 40 PM" src="https://user-images.githubusercontent.com/10556275/101274439-079b9600-37d9-11eb-9538-a584dc7a8eb6.png">

**Comment by tschaffter** [comment]
I have fixed this issue last week (see [code](https://github.com/nlpsandbox/data-node/blob/995a2d9a6b448d58a14c159796de4f7d6cc41a1c/server/openapi_server/controllers/annotation_store_controller.py#L152-L153)). You may need to update the data node on the EC2.

**Comment by thomasyu888** [comment]
Does this [line](https://github.com/nlpsandbox/data-node/blob/develop/docker-compose.yml#L20) need to be updated?

**Comment by thomasyu888** [comment]
@tschaffter I think I do have the newest version of the data node running.  That line of code says that it grabs all annotation stores for datasets that start with the same name.

Is it expected behavior when we ask for annotation stores for "2014-i2b2-20201202", that we also get back annotation stores for datasets "2014-i2b2-202012020-v2", "2014-i2b2-20201202-v3", etc?

**Comment by tschaffter** [comment]
Oh, I see what you mean. I should add a trailing slash line 151 to fix this issue.
