### ISSUE TITLE
Can create an annotation even if the dataset or annotationStore doesn't exist

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node#135]
Creating annotation store
![image](https://user-images.githubusercontent.com/10556275/106102462-6a2a6600-617a-11eb-99f6-cda6a4afd891.png)

Querying for datasets (awesome-dataset doesn't exist)
![image](https://user-images.githubusercontent.com/10556275/106102534-7f9f9000-617a-11eb-9e49-2c6e4442db46.png)

But the annotation stores do exist:
![image](https://user-images.githubusercontent.com/10556275/106102584-947c2380-617a-11eb-9a88-b0404ba6eb5e.png)

**Comment by tschaffter** [comment]
I can reproduce this issue.
