### ISSUE TITLE
Make datasets portable

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node#145]
If a note is accidentally deleted

- A submission can no longer be linked to the noteId (which means all stored submissions will no longer have a link to a note)
- The goldstandard will also be missing a note.
- The note can be replaced, but it would have a new noteId

_P.S. yes, I accidentally deleted a note :/_

**Comment by tschaffter** [comment]
The solution seems to allow the user to specify the ID of the note, which can then give its name like `datasets/{datasetId}/fhirStores/{fhirStoreId}/Note/my-note`. This would also make a dataset and its content portable.
