### ISSUE TITLE
Update `db_models`

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node#177]
### Problem description
- [ ] The `IdAnnotation` dbmodel is incorrect.  `id_num` should be `id_number`.  This line of [code](https://github.com/nlpsandbox/data-node/blob/abe8b9da5909f90fee04739ccf41642a27774544/server/openapi_server/dbmodels/text_id_annotation.py#L10)
- [ ] Make sure other dbmodels are synced up to the schemas.

I was able to push the i2b2-phi dataset with some local configuration to `datanode` and `i2b2-phi-dataset` Rmarkdown file.  As far as I know, there shouldn't be other `dbmodel` issues, but im not certain all the `*types` are accounted for in the dataset.

**Comment by tschaffter** [comment]
@thomasyu888 This is the result of an aggressive commit review. :-P
