### ISSUE TITLE
Get annotations causes internal error.

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node#92]
This doesn't work:
<img width="1423" alt="Screen Shot 2020-11-26 at 8 51 56 AM" src="https://user-images.githubusercontent.com/10556275/100295483-b44d6a80-2fc4-11eb-91d3-cfae3ce8260a.png">

But this works:
<img width="1390" alt="Screen Shot 2020-11-26 at 8 53 01 AM" src="https://user-images.githubusercontent.com/10556275/100295542-d0e9a280-2fc4-11eb-8758-eb59ed609d09.png">

**Comment by thomasyu888** [comment]
Both annotationStores exist:
![Uploading Screen Shot 2020-11-26 at 8.53.48 AM.png…]()

**Comment by tschaffter** [comment]
Related to #93
